/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Connect.SQLServerProvider;
import DAO.DAO_NHANVIEN;
import GUI.HOADON_GUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {
 private SQLServerProvider cn;
    private Connection conn;
    PreparedStatement preparedStatement;
    ResultSet resultSet;
    private int maNV;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         this.setLocationRelativeTo(null);
        cn = new SQLServerProvider();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDN = new javax.swing.JTextField();
        btnDN = new javax.swing.JButton();
        btnThemTK = new javax.swing.JButton();
        btnQuenMK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JPassworđN = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 122, 123, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 168, 123, 60));
        getContentPane().add(txtDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 176, 40));

        btnDN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDN.setForeground(new java.awt.Color(153, 102, 255));
        btnDN.setText("Login");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        getContentPane().add(btnDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 105, 40));

        btnThemTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemTK.setForeground(new java.awt.Color(255, 0, 255));
        btnThemTK.setText("Thêm tài khoản");
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 261, 140, 40));

        btnQuenMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuenMK.setForeground(new java.awt.Color(0, 153, 51));
        btnQuenMK.setText("Quên mật khẩu");
        btnQuenMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMKActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 261, -1, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 91, 50, 60));
        getContentPane().add(JPassworđN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 176, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nenlogin.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 64, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nennhanvien1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:

//        String user = txtDN.getText().trim();
//        String pass = JPassworđN.getText().trim();
//        System.out.println("Username: " + user);
//        System.out.println("Password: " + pass);
//
//        if (user.isEmpty() || pass.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Không để thông tin trống!");
//            return;
//        }
//
//        Connection conn = null;
//        PreparedStatement ps = null;
//        ResultSet rs = null;
//        try {
//            conn = cn.open();
//            if (conn == null) {
//                JOptionPane.showMessageDialog(this, "Không thể kết nối đến cơ sở dữ liệu.");
//                return;
//            }
//
//            String sql_dk = "SELECT * FROM TAIKHOAN WHERE TENTAIKHOAN = ? AND MATKHAU = ?";
//            ps = conn.prepareStatement(sql_dk);
//            ps.setString(1, user);
//            ps.setString(2, pass);
//
//            rs = ps.executeQuery();
//            if (rs.next()) {
//            
//                String tentaikhoan = rs.getString("TENTAIKHOAN");
//                
//                // Kiểm tra xem có phải là admin không
//                boolean isAdmin = tentaikhoan.equals("admin");
//                if (isAdmin) {
//                    Menu m=new Menu();
//                    m.setVisible(true);
//                } else {
//                    Menu m=new Menu();
//                    m.setVisible(true);
//                    m.hideNhanVienMenuItem(); // Ẩn chức năng nhân viên
//                    
//                 
//                }
//                this.dispose();
//                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
//                
//            } else {
//                JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!");
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi đăng nhập: " + e.getMessage());
//        } finally {
//            try {
//                if (rs != null) rs.close();
//                if (ps != null) ps.close();
//                if (conn != null) conn.close();
//            } catch (SQLException ex) {
//                ex.printStackTrace();
//            }
//        }
       
    String user = txtDN.getText().trim();
        String pass = new String(JPassworđN.getPassword()).trim(); 
        System.out.println("Username: " + user); 
        System.out.println("Password: " + pass);

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không để thông tin trống!");
        return;
    }

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    try {
        conn = cn.open();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối đến cơ sở dữ liệu.");
            return;
        }

        String sql_dk = "SELECT tk.MANV, nv.TENNV FROM TAIKHOAN tk INNER JOIN NHANVIEN nv ON tk.MANV = nv.MANV WHERE tk.TENTAIKHOAN = ? AND tk.MATKHAU = ?";
        ps = conn.prepareStatement(sql_dk);
        ps.setString(1, user);
        ps.setString(2, pass);

        rs = ps.executeQuery();
        if (rs.next()) {
            int manv = rs.getInt("MANV");
            String tenNV = rs.getString("TENNV");
             String maNV = String.valueOf(manv);

            boolean isAdmin = user.equals("admin");
            Menu menuFrame = new Menu(tenNV, maNV, isAdmin);
            menuFrame.setVisible(true);
            
           // HOADON_GUI hoadon_gui=new HOADON_GUI(tenNV);
           // hoadon_gui.setVisible(true);
            
            this.dispose();
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi đăng nhập: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
        
    }//GEN-LAST:event_btnDNActionPerformed

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        // TODO add your handling code here:
        Register r=new Register();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnQuenMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMKActionPerformed
        // TODO add your handling code here:
        QuenMatKhau q=new QuenMatKhau();
        q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuenMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPassworđN;
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnQuenMK;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtDN;
    // End of variables declaration//GEN-END:variables
}
